### ISSUE TITLE
Building the template for x86_64 or VM

### ISSUE THREAD

**Issue by skanduru** [cresset-template/cresset#29]
Hi 

Thanks for the detailed steps on building and documentation.  Can I make the build image for intel desktop or VM ? In case I use (build/train) on a VM what are the TARGET_ARCH options that needs to be given ?

Thank you so much
Srini

**Comment by veritas9872** [comment]
The default settings are for Intel x86_64, which is what most people use. To build everything, do the following.

1. Run `make env` to create a `.env` file.
2. Edit the `.env` file to add `CCA` and other necessary variables for the `full` service in `docker-compose.yaml`.
3. Edit the `docker-compose.yaml` file's `full` service to add volumes, ports, etc. as necessary for your application.
4. Edit the `reqs/apt-train.requirements.txt` and `pip-train.requirements.txt` files to include the libraries necessary for your application. Please do not remove packages marked as essential packages.
5. Run `make up` to start the build.
6. Take a break. The first build will take some time.
7. After the build has finished and assuming that there are no bugs (usually driver mismatch issues) run `make exec` to enter the container.
8. If there has been a CUDA version mismatch or driver mismatch bug, change the `.env` file or `docker-compose.yaml` file to use the appropriate version of CUDA, cuDNN, etc.
9. Run `make rebuild` to rebuild the image.
10. Take a short break. The second build is much faster than the first build due to caching.
11. Run `make exec` and start coding.

**Comment by veritas9872** [comment]
@skanduru I hope that the information helps. It shows instructions for the most commonly envountered situations so it may seem a bit long. However, most users only need to deal with 8 or so on the first installation and use 3 afterwards.

**Comment by skanduru** [comment]
Thank you very much .. Appreciate it.  I am trying to learn pytorch and this will give a good entry point I think with a good templated package.

**Comment by veritas9872** [comment]
@skanduru No CCA is an attribute of the hardware, not the software. CUDA version should be 11.3.1 for PyTorch version v1.10.2.

**Comment by skanduru** [comment]
Thanks for the clarification!
